In [3]:
import numpy as np

In [6]:
#using np.array
A = np.array([
    [1, 1, 1],
    [2, 1, -1],
    [-1, 1, 1]
])

B = np.array([60, 50, 20]).reshape(-1, 1)

np.linalg.inv(A).dot(B)

array([[20.],
       [25.],
       [15.]])

In [7]:
np.linalg.solve(A, B)

array([[20.],
       [25.],
       [15.]])

## another way 

In [15]:
A = np.matrix([1, 1, 1])
B = np.array([60])

In [16]:
Apinv = np.linalg.pinv(A)
Apinv

matrix([[0.33333333],
        [0.33333333],
        [0.33333333]])

In [17]:
Apinv * B

matrix([[20.],
        [20.],
        [20.]])

In [18]:
C = np.matrix([
    [1, 1, 1],
    [2, 1, -1],
    [-1, 1, 1],
    [1, 1, 2]
    ])

In [19]:
D = np.matrix([60, 50, 20, 100]).T

In [20]:
#np.linalg.inv(C) can't use

In [21]:
Cpinv = np.linalg.pinv(C)

In [22]:
Cpinv * D

matrix([[25.71428571],
        [20.        ],
        [24.28571429]])