In [1]:
import numpy as np
from numpy import linalg

# Predetermined
## # of variables < # of equations

In [12]:
m = np.array([
    [1, 1, 1],
    [4,2,1],
    [9,3,1],
    [16,4,1],
    [25,5,1]
])

m

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [13]:
b = np.array([
    1.39, 2.21, 3.21, 3.39, 5.81
]).reshape(-1, 1)

b

array([[1.39],
       [2.21],
       [3.21],
       [3.39],
       [5.81]])

In [14]:
np.dot(linalg.inv(np.dot(m.T, m)), np.dot(m.T, b))

array([[ 0.17 ],
       [-0.018],
       [ 1.386]])

In [17]:
(linalg.inv(m.T.dot(m))).dot(m.T.dot(b))

array([[ 0.17 ],
       [-0.018],
       [ 1.386]])

# Underdetermined (Backus & Gillbert method)
## # of variables > # of equations

In [4]:
A = np.array([
    [1, 1, 1],
    [1, -1, 2]
])

b = np.array([
    3, -1
]).reshape(-1, 1)

In [5]:
np.dot(A.T, linalg.inv(A.dot(A.T))).dot(b)

array([[0.78571429],
       [2.07142857],
       [0.14285714]])

In [7]:
A = np.array([
    [1, 1, 1]
])

b = np.array([
    60, 
]).reshape(-1, 1)

np.dot(A.T, linalg.inv(A.dot(A.T))).dot(b)

array([[20.],
       [20.],
       [20.]])

In [10]:
linalg.pinv(A)*b

array([[20.],
       [20.],
       [20.]])